# Generated by Django 5.1.2 on 2024-11-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
